### ISSUE TITLE
error running mash-docker

### ISSUE THREAD

**Issue by YaCui** [stephenslab/gtexresults#10]
@gaow  Do you have any ideas on this?

$mash-docker uname -sn
Linux MASH
$mash-docker sos run workflows/gtex6_mash_analysis.ipynb
INFO: Running default:
INFO: Running export:
ERROR: [54aa6b62-8dbd-4b49-b26d-8493ef6b4669]: [export]: [export]: Failed to process input statement [item for item in paths(sys.argv) if item.suffix == '.ipynb'], group_by = 1
: name 'sys' is not defined

**Comment by YaCui** [comment]
@gaow 
I fixed the sys problem(above) by changing *ipynb format file by file.

But I found another problem when I run mash-paper_1, do you know what happened?

INFO: Running mash-paper_1:
Loading required package: ashr
gsl: ../gsl/gsl_vector_int.h:180: ERROR: index out of range
Default GSL error handler invoked.
Aborted
ERROR: [fadbf9b8-ecec-477c-8f35-0fb37dfe9ce3]: [mash-paper_1]: [mash-paper_1]:
Failed to execute Rscript .sos/mash-paper_1_0_4afd4a17.R
exitcode=134, workdir=/Users/cuiya/gtexresults/output
---------------------------------------------------------------------------
[mash-paper]: 3 pending steps: mash-paper_2, mash-paper_3, mash-paper_4


cat .sos/mash-paper_1_0_4afd4a17.R

library(mashr) # `mashr` package offers function `extreme_deconvolution`
script.source = sapply(list.files('/opt/mash-paper', pattern = "*.R", full.names=TRUE), source, .GlobalEnv)
z.stat = readRDS('/Users/cuiya/gtexresults/data/MatrixEQTLSumStats.Portable.Z.rds')$strong.z
sfa = readRDS('/Users/cuiya/gtexresults/output/MatrixEQTLSumStats.Portable.Z.sfa.rds')
s.j = matrix(rep(1,ncol(z.stat)*nrow(z.stat)),ncol=ncol(z.stat),nrow=nrow(z.stat))
res = deconvolution.em.with.bovy(z.stat,
                                  as.matrix(sfa$F),
                                  s.j,
                                  as.matrix(sfa$lambda),
                                  K = 3, P = 3)
saveRDS(res, '/Users/cuiya/gtexresults/output/MatrixEQTLSumStats.Portable.Z.coved.K3.P3.rds')

**Comment by gaow** [comment]
@YaCui Thanks for the error report. It looks like the Extreme Deconvolution (ED) routing has failed -- it's an earlier version of ED so it might be tricky to debug and fix, but I'll try to take a look today.

May I ask why you'd like to reproduce the `mash_paper` workflow? That was meant to reproduce the result of our paper (Urbut et al 2019). But we have since polished mash into an R package, [mashr](https://github.com/stephenslab/mashr),  and provide an [updated workflow using flashr + mashr](https://github.com/stephenslab/gtexresults/blob/master/workflows/mashr_flashr_workflow.ipynb) for data analysis. The workflow implements various choices of prior and residual matrix estimates, as well as a parallelled implementation of posterior computation for large data-set. If you would like to understand with a simpler example how mash/mashr work, perhaps you can start with [this vignette](https://stephenslab.github.io/mashr/articles/eQTL_outline.html) instead, then either adapt it, or use the aforementioned flashr+mashr workflow, for your own analysis?

**Comment by YaCui** [comment]
@gaow Thanks for your response. gtex6_mash_analysis.ipynb is enough for my research and easier to follow. So I still want to fix the Extreme Deconvolution (ED) problem. Maybe I will try the new mashr later.  Thank you so much for your help!

**Comment by Junjun-Xu** [comment]
> @gaow Do you have any ideas on this?
> 
> $mash-docker uname -sn Linux MASH $mash-docker sos run workflows/gtex6_mash_analysis.ipynb INFO: Running default: INFO: Running export: ERROR: [54aa6b62-8dbd-4b49-b26d-8493ef6b4669]: [export]: [export]: Failed to process input statement [item for item in paths(sys.argv) if item.suffix == '.ipynb'], group_by = 1 : name 'sys' is not defined

@YaCui 
I would like to know how to fix this error and the reason for this error.
Thanks a lot.
