### ISSUE TITLE
No output from default_3

### ISSUE THREAD

**Issue by guandailu** [stephenslab/gtexresults#15]
Dear authors,

I am trying to run fastqtl_to_mash.ipynb with the command:
sos run ./gtexresults/workflows/fastqtl_to_mash.ipynb --data-list tensorqtlSumStats.list -j 16

but I get the following errors:
ERROR: [default_3]: [default_3]: Output target /group/zhougrp2/dguan/26_eQTL_mapping/04_eQTL_mapping/mashr/test/fastqtl_to_mash_output/tensorqtlSumStats.portable.h5 does not exist after the completion of step default_3
[default]: Exits with 1 pending step (default_4)

I carefully check that my input datasets are same as described. I am not quite familiar with sos script, can yu help me figure it out what happened?

Thank you so much!

**Comment by gaow** [comment]
@guandailu the error message you see is a conventional sanity check of workflows at the end of a step; it will quit if the desired output is not generated. The question then is why it did not work ... did you try our minimal working example and see if that works? If so, please make sure your data formats are the same (for example I noticed you used the default column setup but I suspect you need to configure it to fit your dataset? you can run `sos run ./gtexresults/workflows/fastqtl_to_mash.ipynb -h` to see available options). If it still does not work, then does the error happen instantly or it took a while before it occurs? For the latter case, does it have additional error message? If there is no additional error message and it does not happen instantly, perhaps the job was killed by the system due to a lack of resource?

**Comment by guandailu** [comment]
Thanks for your quick response! I just check the example you provided and my input files. I have already figure out the reason, and now it is running successfully. 
Thanks a lot!
