### ISSUE TITLE
Expected running time for H5 conversion process

### ISSUE THREAD

**Issue by ChristopherWilks** [stephenslab/gtexresults#16]
Hi,

Thanks for the tools and all the helpful READMEs/notebooks!

We're attempting to run https://github.com/stephenslab/gtexresults/blob/master/workflows/fastqtl_to_mash.ipynb to convert our own set of 7 tissues into MASH ready files.  

We followed the instructions and got everything installed and running, but now the initial H5 conversion process appears to be taking a lot longer than the ~33 hours mentioned in the notes---it's run for more than 96 hours straight and it looks to be only ~17% through.  

Our gene level FastQTL all-pairs files for each tissue have ~353M gene-SNP rows in them, not sure how comparable that is to the gtex ones. But our compressed files sizes appear to be no more than 2x the size of the GTEx v8 eQTL all-pairs file sizes per tissue (our per-tissue compressed gzipped all-pairs files are 7.2 GBs each).  Of course, the performance may not vary linearly depending on the operations involved in the H5 conversion process (e.g. the gene grouping).

Given we only had 7 groups to process, we thought running on a single VM with `JOB_OPTION="-j 32"`, however, the notebook appears to only start up one thread per tissue during the H5 conversion process, is there a way to have multiple threads per tissue?

Also, in general, are there any specific speed tips or modifications to how we're running this that might speed up the H5 conversion process up?

Thanks in advance,
Chris Wilks

**Comment by gaow** [comment]
@ChristopherWilks you are correct that I dont have the multiple-thread per tissue implementation for these conversions. The scope of our analysis was 35000 genes by (on average) 5000 cis-variants per gene. So that should be 100M per tissue. That means 96hrs should roughly be how long it should take to finish your analysis. 

One thing you could check is perhaps if the computer is using 100% CPU in the process? If you run it on a computer system with slow (network based) disk setup the CPU will not be fully utilized since the disk access is a concern, and thus the proposed additional parallelization may also not help. 

The data processing approach was developed many years ago and there should definitely be some better approaches at this point to tackle the problem. We might indeed update the approach as we need them down the road although this is not a priority. However if you are interested we might work on it with your contributions? If you want to do that please email me (at wang.gao at columbia.edu)

**Comment by ChristopherWilks** [comment]
@gaow thanks for the very rapid response!
It's good to know how much data you were running on to compare against.
While our CPUs are maxed at 100%, there may be other issues specific to our environment that are slowing the processing down.

As far as investigating better approaches to the processing, I am thinking about that as well. 
I'll follow up via email if I think I have a feasible approach and if I get the green light from my management to pursue it (we have other higher priorities right now).

Thanks again for the response and for the methods.
